IMAGE_REGISTRY ?= local
IMAGE_TAG      ?= v1

DOCKER         := docker
KUBECTL        := kubectl

PROJECT_NAME := worker-scaler-controller

.PHONY: help
help: ## Show this help message
	@echo "------------------------------------------------------------------------"
	@echo "${PROJECT_NAME}"
	@echo "------------------------------------------------------------------------"
	@awk 'BEGIN {FS = ":.*?## "}; $$0 ~ "^[[:alnum:]_/%-]+:.*?## " {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

.PHONY: fmt
fmt: ## Format code
		go fmt ./...

.PHONY: vet
vet: ## Vet code
		go vet ./...

.PHONY: test
test: ## Run unit tests
		go test -short -race -count=1 -v ./...

.PHONY: lint
lint: vet ## Lint code
		@if command -v staticcheck >/dev/null 2>&1; then \
			staticcheck ./...; \
		else \
			echo "staticcheck not installed, skipping (go install honnef.co/go/tools/cmd/staticcheck@latest)"; \
		fi

.PHONY: build-producer
build-producer: ## Build the producer container image
	$(DOCKER) build -f build/Dockerfile --target producer -t $(IMAGE_REGISTRY)/redis-producer:$(IMAGE_TAG) .

.PHONY: build-worker
build-worker: ## Build the worker container image
	$(DOCKER) build -f build/Dockerfile --target worker -t $(IMAGE_REGISTRY)/redis-worker:$(IMAGE_TAG) .

.PHONY: build-controller
build-controller: ## Build the scaler controller container image
	$(DOCKER) build -f build/Dockerfile --target controller -t $(IMAGE_REGISTRY)/scaler-controller:$(IMAGE_TAG) .

.PHONY: build-all
build-all: build-producer build-worker build-controller ## Build producer, worker, and controller images

.PHONY: load-producer
load-producer: build-producer ## Build and load the producer image straight into kind cache
	kind load docker-image $(IMAGE_REGISTRY)/redis-producer:$(IMAGE_TAG) --name worker-scaler

.PHONY: load-worker
load-worker: build-worker ## Build and load the worker image straight into kind cache
	kind load docker-image $(IMAGE_REGISTRY)/redis-worker:$(IMAGE_TAG) --name worker-scaler

.PHONY: load-controller
load-controller: build-controller ## Build and load the controller image straight into kind cache
	kind load docker-image $(IMAGE_REGISTRY)/scaler-controller:$(IMAGE_TAG) --name worker-scaler

.PHONY: load-all
load-all: load-producer load-worker load-controller ## Build and load all images into the kind cluster

.PHONY: deploy-redis
deploy-redis: ## Apply the Redis deployment and service manifests
	$(KUBECTL) apply -f manifests/local-dev/redis.yaml

.PHONY: deploy-worker
deploy-worker: load-worker ## Build, load, and apply the worker deployment
	$(KUBECTL) apply -f manifests/local-dev/worker-deployment.yaml

.PHONY: deploy-controller
deploy-controller: load-controller ## Build, load, and apply the controller deployment and RBAC rules
	$(KUBECTL) apply -f manifests/local-dev/controller.yaml

.PHONY: delete-worker
delete-worker: ## Delete the worker deployment
	$(KUBECTL) delete -f manifests/local-dev/worker-deployment.yaml --ignore-not-found=true

.PHONY: deploy-all
deploy-all: deploy-redis deploy-worker ## Deploy Redis and the Worker

.PHONY: run-producer
run-producer: load-producer ## Run the producer Job inside kind
	-$(KUBECTL) delete -f manifests/local-dev/producer-job.yaml -n worker-scaler 2>/dev/null || true
	$(KUBECTL) apply -f manifests/local-dev/producer-job.yaml

.PHONY: run-controller
run-controller: ## Run the scaler controller locally against the active kubeconfig context
	go run ./cmd/controller/main.go

.PHONY: clean
clean: ## Delete local host docker images generated by this Makefile
	-$(DOCKER) rmi $(IMAGE_REGISTRY)/redis-producer:$(IMAGE_TAG) 2>/dev/null || true
	-$(DOCKER) rmi $(IMAGE_REGISTRY)/redis-worker:$(IMAGE_TAG) 2>/dev/null || true
	-$(DOCKER) rmi $(IMAGE_REGISTRY)/scaler-controller:$(IMAGE_TAG) 2>/dev/null || true
