apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-controller
  namespace: worker-scaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-scaler-role
  namespace: worker-scaler
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaler-controller-binding
  namespace: worker-scaler
subjects:
  - kind: ServiceAccount
    name: scaler-controller
    namespace: worker-scaler
roleRef:
  kind: Role
  name: deployment-scaler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaler-controller
  namespace: worker-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaler-controller
  template:
    metadata:
      labels:
        app: scaler-controller
    spec:
      serviceAccountName: scaler-controller
      containers:
        - name: controller
          image: local/scaler-controller:v1
          imagePullPolicy: Never
          env:
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: SYNC_PERIOD
              value: "5s"
            - name: TASKS_PER_WORKER
              value: "10"
            - name: MAX_WORKERS
              value: "5"
            - name: K8S_NAMESPACE #
              value: "worker-scaler"
