apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-controller
  namespace: worker-scaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-scaler-role
  namespace: worker-scaler
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaler-controller-binding
  namespace: worker-scaler
subjects:
  - kind: ServiceAccount
    name: scaler-controller
    namespace: worker-scaler
roleRef:
  kind: Role
  name: deployment-scaler-role
  apiGroup: rbac.authorization.k8s.io
