apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-worker
  namespace: worker-scaler
  labels:
    app: redis-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-worker
  template:
    metadata:
      labels:
        app: redis-worker
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker
          image: docker.io/alesr/redis-worker:1780001755
          imagePullPolicy: Always
          env:
            - name: REDIS_ADDR
              value: "redis:6379"
              # changing the number of goroutines in the workerpool
              # should be followed be an increment in the number of desidered
              # tasks per worker (in pods) in the controller deployment manifest
              # to avoid over/under provisioning
            - name: WORKER_CONCURRENCY
              value: "10"
            - name: POOL_BUFFER_SIZE
              value: "100"
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            exec:
              command: ["/bin/true"] # todo: implement healthcheck
            initialDelaySeconds: 5
            periodSeconds: 10
